<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="1" failed="4" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-01-05T00:31:38 IST" name="Default suite" finished-at="2024-01-05T00:31:42 IST" duration-ms="4449">
    <groups>
    </groups>
    <test started-at="2024-01-05T00:31:38 IST" name="Default test" finished-at="2024-01-05T00:31:42 IST" duration-ms="4449">
      <class name="com.restcalls.org.GetCall">
        <test-method is-config="true" signature="setUPSuite()[pri:0, instance:com.restcalls.org.GetCall@22f59fa]" started-at="2024-01-05T00:31:37 IST" name="setUPSuite" finished-at="2024-01-05T00:31:38 IST" duration-ms="268" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUPSuite -->
        <test-method is-config="true" signature="setUp(java.lang.reflect.Method)[pri:0, instance:com.restcalls.org.GetCall@22f59fa]" started-at="2024-01-05T00:31:38 IST" name="setUp" finished-at="2024-01-05T00:31:38 IST" duration-ms="8" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.restcalls.org.GetCall.getEmployee1(java.util.Map)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="getEmployee1(java.util.Map)[pri:0, instance:com.restcalls.org.GetCall@22f59fa]" started-at="2024-01-05T00:31:38 IST" name="getEmployee1" data-provider="getData1" finished-at="2024-01-05T00:31:41 IST" duration-ms="3056" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{first_Name=srinadhu, last_Nmae=jagan, id=1}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[
expected: 201
 but was: 200]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 
expected: 201
 but was: 200
at com.restcalls.org.GetCall.getEmployee1(GetCall.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getEmployee1 -->
        <test-method is-config="true" signature="teststatus(org.testng.ITestResult)[pri:0, instance:com.restcalls.org.GetCall@22f59fa]" started-at="2024-01-05T00:31:41 IST" name="teststatus" finished-at="2024-01-05T00:31:41 IST" duration-ms="1" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=getEmployee1 status=FAILURE method=GetCall.getEmployee1(java.util.Map)[pri:0, instance:com.restcalls.org.GetCall@22f59fa] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teststatus -->
        <test-method is-config="true" signature="setUp(java.lang.reflect.Method)[pri:0, instance:com.restcalls.org.GetCall@22f59fa]" started-at="2024-01-05T00:31:41 IST" name="setUp" finished-at="2024-01-05T00:31:41 IST" duration-ms="1" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.restcalls.org.GetCall.getEmployee1(java.util.Map)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="getEmployee1(java.util.Map)[pri:0, instance:com.restcalls.org.GetCall@22f59fa]" started-at="2024-01-05T00:31:41 IST" name="getEmployee1" data-provider="getData1" finished-at="2024-01-05T00:31:41 IST" duration-ms="94" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{first_Name=brock, last_Nmae=lesnar, id=3}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[
expected: 201
 but was: 200]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 
expected: 201
 but was: 200
at com.restcalls.org.GetCall.getEmployee1(GetCall.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getEmployee1 -->
        <test-method is-config="true" signature="teststatus(org.testng.ITestResult)[pri:0, instance:com.restcalls.org.GetCall@22f59fa]" started-at="2024-01-05T00:31:41 IST" name="teststatus" finished-at="2024-01-05T00:31:41 IST" duration-ms="2" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=getEmployee1 status=FAILURE method=GetCall.getEmployee1(java.util.Map)[pri:0, instance:com.restcalls.org.GetCall@22f59fa] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teststatus -->
        <test-method is-config="true" signature="setUp(java.lang.reflect.Method)[pri:0, instance:com.restcalls.org.GetCall@22f59fa]" started-at="2024-01-05T00:31:41 IST" name="setUp" finished-at="2024-01-05T00:31:41 IST" duration-ms="3" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.restcalls.org.GetCall.getEmployee1(java.util.Map)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="getEmployee1(java.util.Map)[pri:0, instance:com.restcalls.org.GetCall@22f59fa]" started-at="2024-01-05T00:31:41 IST" name="getEmployee1" data-provider="getData1" finished-at="2024-01-05T00:31:41 IST" duration-ms="67" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{first_Name=sachin, last_Nmae=tendulkar, id=10}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[
expected: 201
 but was: 200]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 
expected: 201
 but was: 200
at com.restcalls.org.GetCall.getEmployee1(GetCall.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getEmployee1 -->
        <test-method is-config="true" signature="teststatus(org.testng.ITestResult)[pri:0, instance:com.restcalls.org.GetCall@22f59fa]" started-at="2024-01-05T00:31:41 IST" name="teststatus" finished-at="2024-01-05T00:31:41 IST" duration-ms="1" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=getEmployee1 status=FAILURE method=GetCall.getEmployee1(java.util.Map)[pri:0, instance:com.restcalls.org.GetCall@22f59fa] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teststatus -->
        <test-method is-config="true" signature="setUp(java.lang.reflect.Method)[pri:0, instance:com.restcalls.org.GetCall@22f59fa]" started-at="2024-01-05T00:31:41 IST" name="setUp" finished-at="2024-01-05T00:31:41 IST" duration-ms="1" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.restcalls.org.GetCall.getEmployee1(java.util.Map)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="getEmployee1(java.util.Map)[pri:0, instance:com.restcalls.org.GetCall@22f59fa]" started-at="2024-01-05T00:31:41 IST" name="getEmployee1" data-provider="getData1" finished-at="2024-01-05T00:31:41 IST" duration-ms="64" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{first_Name=pawan, last_Nmae=kalyan, id=4}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[
expected: 201
 but was: 200]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 
expected: 201
 but was: 200
at com.restcalls.org.GetCall.getEmployee1(GetCall.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getEmployee1 -->
        <test-method is-config="true" signature="teststatus(org.testng.ITestResult)[pri:0, instance:com.restcalls.org.GetCall@22f59fa]" started-at="2024-01-05T00:31:41 IST" name="teststatus" finished-at="2024-01-05T00:31:41 IST" duration-ms="1" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=getEmployee1 status=FAILURE method=GetCall.getEmployee1(java.util.Map)[pri:0, instance:com.restcalls.org.GetCall@22f59fa] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teststatus -->
        <test-method signature="getEmployees()[pri:0, instance:com.restcalls.org.GetCall@22f59fa]" started-at="2024-01-05T00:31:41 IST" name="getEmployees" finished-at="2024-01-05T00:31:42 IST" duration-ms="1020" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getEmployees -->
        <test-method is-config="true" signature="setUp(java.lang.reflect.Method)[pri:0, instance:com.restcalls.org.GetCall@22f59fa]" started-at="2024-01-05T00:31:41 IST" name="setUp" finished-at="2024-01-05T00:31:41 IST" duration-ms="0" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.restcalls.org.GetCall.getEmployees()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method is-config="true" signature="teststatus(org.testng.ITestResult)[pri:0, instance:com.restcalls.org.GetCall@22f59fa]" started-at="2024-01-05T00:31:42 IST" name="teststatus" finished-at="2024-01-05T00:31:42 IST" duration-ms="0" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=getEmployees status=SUCCESS method=GetCall.getEmployees()[pri:0, instance:com.restcalls.org.GetCall@22f59fa] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teststatus -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.restcalls.org.GetCall@22f59fa]" started-at="2024-01-05T00:31:42 IST" name="tearDown" finished-at="2024-01-05T00:31:42 IST" duration-ms="399" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.restcalls.org.GetCall -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
